### ISSUE TITLE
Filter eBPF to reduce noise and increase performance 

### ISSUE THREAD

**Issue by emilwareus** [arvos-dev/arvos#13]

**Comment by moule3053** [comment]
I found it very challenging to push the filtering on symbols back to the eBPF/kernel space because of a number of eBPF limitations, such as:

- Limit on the number of eBPF bytecode instructions (https://ebpf.io/blog/ebpf-updates-2021-02#did-you-know-program-size-limit). This limit can easily be reached with the number of conditions to check whether an invoked symbol is in the vulnerability dataset.
- Size of stack space limited to 512 bytes (https://ebpf.io/blog/ebpf-updates-2021-02#did-you-know-program-size-limit). This limits the size of symbol names only to 64 characters and leads to a lot of false positives.
- Also eBPF verification may fail if it detects that the program might not terminate even though the number of instructions is below the limit.

**Comment by moule3053** [comment]
A couple of other approaches to improve performance:

- Using a `ring buffer` rather than `perf buffer` (https://www.kernel.org/doc/html/latest/bpf/ringbuf.html). A `ring buffer` shows better performance than an ordinary `perf buffer`. However, it is supported only on Linux kernel versions > 5.8 (https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#5-bpf_ringbuf_output).
- Count events per time period and write only unique events to the ring buffer to reduce the number of events.
